# This will be for test rest ApI with username, password and email

# POST method for testing login users
POST http://127.0.0.1:8000/login
content-type: application/json

{
    "username": "profic",
    "password": "Pass1234"
}

### Signup POST method for new user request

POST http://127.0.0.1:8000/signup
content-type: application/json

{
    "username": "profic1",
    "password": "Pass1234",
    "email": "profic@gmail.com"
}


### test_token request 
GET http://127.0.0.1:8000/test_token
content-type: application/json
Authorization: Token d95bcc8c50fe34c8895c84eedaac26695bb0b2b0

